services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: eldercare-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    volumes:
      - ./app/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    networks:
      - eldercare-network

networks:
  eldercare-network:
    driver: bridge