services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: eldercare-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    command: mosquitto -c /mosquitto-no-auth.conf
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: eldercare-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eldercare
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: